feediron/ttrss_plugin-feediron

README.md, init.php, recipes/dorkly.com
Allow recursive fetching of multipages and use a simple caching to reduce load times
=> Enable recusive fetching of multipage

recipes/spiegel_de
recipe for spiegel_de, with up to 5 comments
=> recipe for spiegel_de, with up to 5 comments

recipes/massivelyop_com
=> Add recipe for massivelyop.com

recipes/sankakucomplex
Added a recipe for sankakucomplex.com
=> Added Sankaku Recipe

recipes/abgeordnetenwatch_de, recipes/androidpolice_com, recipes/chefkoch_de, recipes/der-farang_com, recipes/der-postillon_com, recipes/epitition_bundestag_de, recipes/merkur_de, recipes/scienexx_de, recipes/sz_de, recipes/theoatmeal_com, recipes/toonpool_com
=> merge please

init.php
Prior pull request was a bit per-mature.
I Added test view error check clearing input field on json errors then fixed error I added with blank test field kicking up a json error rather than just fetching existing configuration. Cleaned up my code a bit as I introduced an unnecessary extra if function.
=> Test view error check

recipes/heise_de_developer, recipes/heise_de_newsticker, recipes/heise_de_technology_review, recipes/heise_de_telepolis
Recipes generated through the export functionality this time (instead of writing them manually).
Thanks @kuestenjunge.
=> Fix recipe names for heise.*

Logger.php
Makes reviewing the Testing panel log easier
=> Add HTML5 details tag to logger

init.php
Closes #47
-  Url's split using | as Delimiter
```json
"example.com|example.net" {
...
}
```
=> Add multi-url for config

README.md, init.php
Fixes #22 
- Moved tidy fuction to processArticle fuction
- Minor Auto-indented code + readability of code
=> Add html tidy option

init.php
=> skip missing xpath in array

README.md, init.php
=> Added tidy-source option

recipes/dailymail.co.uk
Filter for articles on dailymail.co.uk
Fixes #
- 
- 
-
=> dailymail.co.uk filter

recipes/yahoo.com
=> Yahoo.com Filter

recipes/foxnews.com
=> foxnews.com article filter

recipes/dailymail.co.uk
Sorry, not sure why it had my old filter in there
Current only blocks middle "extras/related"
Update Blocks both middle and bottom
Fixes #
- 
- 
-
=> Fix filter

recipes/thehill.com
Formating fix for thehill.com
Fixes #
- 
- 
-
=> Filter for thehill.com

recipes/breitbart.com
Fixes filtering on breitbart.com
Fixes #
- 
- 
-
=> Filter for Breitbart.com

recipes/nbc12.com
Filter fix for NBC12.com
Fixes #
- 
- 
-
=> Fix for NBC12.com

recipes/fredericksburg.com
Fix the filtering on fredericksburg.com
Fixes #
- 
- 
-
=> Filter for Fredericksburg.com

recipes/bbc.com
=> Filter for the BBC

recipes/theguardian.com
Just finaly figured out how to use the testing feature, so my filters should come out faster and more reliable since I dont have to wait for my feed to update to check it.
Fixes #
- 
- 
-
=> Filter for theguardian.com

recipes/aljazeera.com
=> Updated filter for aljazeera.com

recipes/abgeordnetenwatch.de
Forgive me if I missed any content as I do not know this language
Website: abgeordnetenwatch.de
Fixes #
- 
- 
-
=> Updated filter for abgeordnetenwatch.de

recipes/bgr.com
=> Filter for BGR.com

recipes/bangkokpost.com
Looks like it's still good, just made 1 quick edit to fix
Fixes #
- 
- 
-
=> Filter for bangkokpost.com

recipes/nakedsecurity.sophos.com
Filter for security feed https://nakedsecurity.sophos.com/feed/
Fixes #
- 
- 
-
=> Filter for nakedsecurity.sophos.com

recipes/secureworks.com
Filter for https://www.secureworks.com/rss?feed=research&category=threat-analysis
and
https://www.secureworks.com/rss?feed=blog&category=threats-and-defenses
Fixes #
- 
- 
-
=> Filter for secureworks.com

recipes/threatpost.com
=> Filter for threatpost.com

Logger.php
=> Switch log exception from Warning to Notice

init.php
`rel2abs` wasn't properly handling the case where both the base and link
included a fragment/query string. In this case, the resulting URL would
include the fragment/query string from both the base URL and link.
`rel2abs` has been replaced with an implementation that closely follows
the method outlined in [RFC 3986 section 5.2][0] for converting a
relative URI to an absolute one, given a known base URI.
Example
-------
Base: `https://example.org?key=value`
Relative link: `?key2=value2`
Previous result: `https://example.org?key=value?key2=value2`
Correct result: `https://example.org?key2=value2`
[0]: https://tools.ietf.org/html/rfc3986#section-5.2
=> Fix resolving relative links to absolute links

init.php
It confused me that the version number wasn't changing in the settings panel and found out that the string hasn't been updated.
=> update version string

recipes/der-postillon_com, recipes/explosm.net
Website: der-postillion.com
Website: explosm.net
- new recipe
- feedburner links were not recognized
- article was wrapped inside an empty <a>-tag
=> Fix der-postillion.com, Added explosm.net

Logger.php, init.php
Hi, I've changed a PHP keyword to comply with [this standard](https://www.php-fig.org/psr/psr-2/#25-keywords-and-truefalsenull) in PSR2. It's admittedly a small fix but I hope it helps!
=> Change PHP keywords to comply with PSR2

recipes/bleepingcomputer_com
New recipe for bleepingcomputer.com
=> Recipe for bleepingcomputer.com

recipes/androidpolice_com
updated AndroidPolice to load main article image from the img-hero tags outside the main article div
=> updated AndroidPolice to load main article image (hero)

recipes/eetimes.com
Website: eetimes.com
This mainly allows to display the multipage articles into one single page. 
Everything else looks fine, I didn't spot any issues in a few weeks I've been running this.
=> add eetimes.com recipe

init.php
deprecated" warning
NOTICE!!!
All rule submissions should be done in the https://github.com/feediron/feediron-recipes repository.
Fixes #
- use non deprecated syntax to access array elements
=> Fix PHP deprecated warning

README.md, init.php
=> Defaults dev

README.md
Updated tidy-source anchor link in the documentation.
=> update tidy-source anchor link

filters/fi_mod_readability/README.md, filters/fi_mod_readability/init.php
- Add Excerpt option to Readability
- Add cleanup explanation to Readme
- Fixed the inability to prepend and append images in one operation
- Better readability of code through switch statements rather than if statements
=> Readbility dev

README.md, init.php
Added new "pages" option to multipage
=> add recursive page limiter

filters/fi_mod_readability/init.php, filters/fi_mod_tags_regex/init.php, filters/fi_mod_tags_search/init.php, filters/fi_mod_tags_xpath/init.php, filters/fi_mod_xpath/init.php, init.php
* Handle unknown number args in hook_prefs_tabs
* Limit array based warning notices
=> Php8 support

filters/fi_mod_readability/init.php, filters/fi_mod_readability/php-readability/JSLikeHTMLElement.php, filters/fi_mod_readability/php-readability/LICENSE.md, filters/fi_mod_readability/php-readability/README.md, filters/fi_mod_readability/php-readability/Readability.php
Fix composer autoloader
Update internal readability from https://github.com/j0k3r/php-readability/
=> Redability dev

README.md
Fix #186
NOTICE!!!
All rule submissions should be done in the https://github.com/feediron/feediron-recipes repository.
Fixes #
-
-
-
=> Update git url
