init.php
e.g. if you have an xpath that returns a single html element, like <img src='mycomic.png'>, it has no children, so getInnerHtml() returns nothing and the entire page gets used instead.
=> Fixes extremely specific xpath case

recipes/heise_de_developer, recipes/heise_de_newsticker, recipes/heise_de_technology_review, recipes/heise_de_telepolis
Just some old but extended -- remove footer for heise.de/(newsticker|tr) -- and some new -- heise.de/(developer|tp) -- recipes for FeedIron. First preliminary versions.
=> New recipes for heise.de feeds: newsticker, developer, tr, and tp

Json.php
Function json_format adds unnecessary spaces and newlines to the JSON.
So, added standart mechanism for pretty printing.
=> Replaces JSON format function

Logger.php
Use of undefined constant LOG_NONE - assumed 'LOG_NONE' (this will throw an Error in a future version of PHP)
1. plugins/feediron/Logger.php(12): ttrss_error_handler(2, Use of undefined constant LOG_NONE - assumed 'LOG_NONE' (this will throw an Error in a future version of PHP), plugins/feediron/Logger.php, 12, Array)
2. plugins/feediron/RecipeManager.php(14): get()
3. plugins/feediron/PrefTab.php(7): loadAvailableRecipes()
4. plugins/feediron/init.php(581): get_pref_tab({...}, false)
5. backend.php(123): index()
=> Prevent warning Use of undefined constant LOG_NONE

README.md, composer.json, init.php
Adds the ability to use [readability.php](https://github.com/andreskrey/readability.php) if installed (via composer)
Configuration options that would be good to implement:
=> Add Readability.php optionality

init.php
Fixes occasional inclusion of `&quote;` or `"` in charset fetched through preg_match as seen in [pbfcomics feed](http://pbfcomics.com/feed/)
=> Add quote escapes to charset detection

README.md, init.php, recipes/hiveworks
First commit:
I wanted a rule for RSS feeds authored by sites belonging to the hiveworks network. They have in common the author field of the feed. Unfortunately, I cannot write a single rule for them because they have completely unrelated domains.
This makes feediron trigger a rule if the key in the config matches the author feed, and not only the url.
I also added the corresponding recipe.
Second commit: (The two commits could be split in two PRs if you insist by the way.)
I ran into #73 while using this recipe: xpath can select an attribute node, which is refused by appendChild. This commit replaces it by a text node.
I have ran this for more than a week without problems, now.
Please review carefully, I don't speak PHP.
=> Trigger rule according to author

recipes/xkcd_com
Website: xkcd.com
- Support for linked images as in the comic from 2019-02-27: https://xkcd.com/2116
=> Fix for linked images at xkcd

init.php
In the specific case where fetching more pages is stopped due to finding
a duplicate link, the link to the page where the duplicate found was not
being returned.
This manifested as the last page of a multipage article not being
processed.
This commit fixes this by returning an array with the current link in it
when finding a duplicate link.
=> Fix missing last page when using multipage

recipes/arstechnica
Website: arstechnica.com
The regex is a bit ugly but does the job. Here's what an image gallery looks like in HTML (cleaned up a bit, placeholder text in `[]`'s)
```html
<ul>
<li data-thumb="[tiny image url]" data-src="[fullsize image url]" data-responsive="[list of image urls followed by sizes]" data-sub-html="#caption-[caption id]">
<figure style="height:[something]px;">
<div class="image" style="background-image:url('[midsize image url]'); background-color:#000"></div>
<figcaption id="caption-[caption id]">
<span class="icon caption-arrow icon-drop-indicator"></span>
<div class="caption">[some caption]</div>
<div class="credit"><span class="icon icon-camera"></span>[some person]</div>
</figcaption>
</figure>
</li>
[many more <li></li>'s]
</ul>
```
The regex aims to pull out `[fullsize …
=> Update Arstechnica recipe to include image galleries

init.php
When a xpath ruleset is made of several rules, and, for instance, the second rule return a void (because the underlying website as an optional HTML node for example), then the $basenode value will be filled with the node returned by the first rule of the set.
So, to correct this and avoid repetitions into the result, the basenode=false have to be inside the rule's loop.
Website: http://secouchermoinsbete.fr/
ATOM: https://secouchermoinsbete.fr/feeds.atom
Rule:
~~~json
"secouchermoinsbete.fr": {
"type": "xpath",
"xpath": [
"article[@class='anecdote']\/p[@class='summary']",
"article[@class='anecdote']\/p[@class='details']",
"div[@id='sources']"
],
"join_element": "<br><br>"
}
~~~
=> [Bug correction] Reset basenode at each xpath rule

recipes/hackaday.com
All the article doesn't appear in the feed by default, and pictures are
missing.
This recipe fetches the whole article, along with the pictures.
Website: hackaday.com
=> add hackaday.com recipe

init.php
Was tipped off by a warning in the console:
```
strpos(): Non-string needles will be interpreted as strings in the future.
Use an explicit chr() call to preserve the current behavior
```
=> Add missing articleMarker declaration

filters/fi_mod_readability/README.md, filters/fi_mod_readability/init.php
- Add support for the SummonCthulhu option of readability.php, which cleans up <script> tags.
If a <script> tag contains some embedded HTML, it can mangle the resulting output. Readbility.php provides a workaround for this with the SummonCthulhu option as explained in its [README](https://github.com/andreskrey/readability.php#known-issues)
As seen in the [source](https://github.com/andreskrey/readability.php/blob/84dc70df66978d5f778f31cbc41efcc1c190ea6f/src/Readability.php#L272) this just performs the following:
```php
preg_replace('/<script\b[^>]*>([\s\S]*?)<\/script>/', '', $html);
```
so it is already possible to do by adding that regex to the "cleanup" option, but it would be nice to make it a full-fledged option itself.
=> add support for summonCthulhu option

init.php
I updated TTRSS with PHP8 and got a constant warning with the master branch of Feediron. This change fixed it for me.
=> Fix PHP8 array warning if tidy is not present

init.php
removed unused args for `hook_prefs_tabs` as well
Fixes #175
=> Add returntype to methods to comply with PHPStan changes

filters/fi_mod_xpath/init.php
The method `cleanupNode` uses `$xpath->query` to retrieve a nodelist this can return null and break the following `foreach` resulting in a Warning in the system log like follows:
E_WARNING (2) | plugins.local/feediron/filters/fi_mod_xpath/init.php:95 | foreach() argument must be of type array\|object, bool given 1. plugins.local/feediron/filters/fi_mod_xpath/init.php(95): ttrss_error_handler(2, foreach() argument must be of type array\|object, bool given, plugins.local/feediron/filters/fi_mod_xpath/init.php, 95) 2. plugins.local/feediron/filters/fi_mod_xpath/init.php(41): cleanupNode({DOMXPath}, {DOMElement}, [{"type":"xpath","xpath":"article[contains(@data-article-type,'meldung')]","multipage":{"xpath":"a[contains(@name,'sonderseite.newsticker.bottom.aufeinerseitelesen')]","append":false, …
=> add a check for xpath-query null result

preftab/fi_pref_tab.php
Not sure if this changed with newer ttrss or it's because of some other factor, but the PluginHandler class name is case sensitive and needs to be corrected or you get E_UNKNOWN_METHOD when trying to do anything at all with the pref tab.
NOTICE!!!
All rule submissions should be done in the https://github.com/feediron/feediron-recipes repository.
Fixes #
-
-
-
=> Fix name of op for pref tab

README.md, init.php
Situation: Having a Article link, which needs to be reformatted with regular expressions like:
```json
"reformat": [
{
"type": "regex",
"pattern": "\/\\.html$\/",
"replace": ".amp.html"
}
]
```
If multipage handling is used and configured like:
```json
"multipage": {
"xpath": "ol[@class='list-pages' and not(@id='atoc_line')]\/li\/a[text() != '\u203a']",
"append": true,
"reformat": true // <== this is the new option!
},
```
the corresponding links to the next pages are extracted and fetched in order to append to each others.
Unfortunately, the news paper does provide a link for the next pages, which must be modified as well in order to proper fetch it (otherwise it would …
=> Reformat URLs on Multipage-Handling

init.php
After integration of feediron/ttrss_plugin-feediron#199 for having feature to reformat found subsequent article links, recursive multipage handling mode is failing.
This commit fixes the recursive loop.
Fixes feediron/ttrss_plugin-feediron#201
NOTICE!!!
All rule submissions should be done in the https://github.com/feediron/feediron-recipes repository.
Configuration:
```json
{
"type": "xpath",
"xpath": "div[contains(@class, 'article-content')]",
"multipage": {
"xpath": "nav[contains(@class, 'page-numbers')]\/span\/a[last()]",
"append": true,
"recursive": true
},
"modify": [
{
"type": "regex",
"pattern": "\/<li.*? …
```
=> Fix Recursive fetch after new reformat option
